// react/atom/textarea.tsx
import { z } from 'zod';
import styles from './textarea.module.scss';
import { useValidation } from '../hooks/useValidation';

export interface TextareaWrapperProps extends React.ComponentProps<'textarea'> {
  value: string;
  className?: string;
  validator?: z.ZodType<unknown>;
  /** Accessible label for screen readers */
  'aria-label'?: string;
  /** ID of element describing the textarea */
  'aria-describedby'?: string;
}

const Textarea: React.FC<TextareaWrapperProps> = ({
  validator,
  value,
  className,
  id,
  ...rest
}) => {
  const textareaId = id || `textarea-${Math.random().toString(36).slice(2, 9)}`;
  const errorId = `${textareaId}-error`;
  const { message, statusClass, validate } = useValidation(validator);

  return (
    <div className={`${styles.style} ${className}`}>
      <textarea
        id={textareaId}
        {...rest}
        value={value}
        className={`${statusClass} ${className}`}
        onKeyUp={() => validate(value)}
        aria-invalid={statusClass === 'danger' ? true : undefined}
        aria-describedby={message ? errorId : rest['aria-describedby']}
      />
      {validator && message !== '' && (
        <div id={errorId} className="validator" role="alert">
          {message}
        </div>
      )}
    </div>
  );
};

export default Textarea;

// svelte/atom/Textarea.svelte
<script lang="ts">
  import type { HTMLTextareaAttributes } from 'svelte/elements';
  import type { z } from 'zod';
  import { createValidation } from '../stores/validation';
  import styles from './textarea.module.scss';

  interface Props extends HTMLTextareaAttributes {
    /** Textarea value */
    value?: string;
    /** Zod validator */
    validator?: z.ZodType<unknown>;
    /** Element reference for bind:this */
    element?: HTMLTextAreaElement;
  }

  let {
    validator,
    value = $bindable(''),
    class: className = '',
    id,
    element = $bindable(),
    ...rest
  }: Props = $props();

  const { message, statusClass, validate } = createValidation(validator);

  let textareaId = id || `textarea-${Math.random().toString(36).slice(2, 9)}`;
  let errorId = `${textareaId}-error`;

  function handleKeyup() {
    validate(value);
  }

  let textareaClass = $derived([$statusClass, className].filter(Boolean).join(' '));
</script>

<div class="{styles.style} {className}">
  <textarea
    bind:this={element}
    id={textareaId}
    bind:value
    class={textareaClass}
    onkeyup={handleKeyup}
    aria-invalid={$statusClass === 'danger' ? true : undefined}
    aria-describedby={$message ? errorId : rest['aria-describedby']}
    {...rest}
  ></textarea>
  {#if validator && $message !== ''}
    <div id={errorId} class="validator" role="alert">
      {$message}
    </div>
  {/if}
</div>
