// svelte/molecule/Pagination.svelte
<script lang="ts">
  import styles from './pagination.module.scss';

  interface Props {
    /** Current page number */
    currentPage: number;
    /** Total number of pages */
    totalPages: number;
    /** Page change callback */
    onpagechange: (page: number) => void;
    /** Maximum visible page numbers */
    maxVisiblePages?: number;
  }

  let {
    currentPage = $bindable(1),
    totalPages,
    onpagechange,
    maxVisiblePages = 5,
  }: Props = $props();

  function getPageNumbers(): number[] {
    const pages: number[] = [];
    const startPage =
      Math.floor((currentPage - 1) / maxVisiblePages) * maxVisiblePages + 1;
    const endPage = Math.min(startPage + maxVisiblePages - 1, totalPages);

    for (let i = startPage; i <= endPage; i++) {
      pages.push(i);
    }

    return pages;
  }

  let pageNumbers = $derived(getPageNumbers());

  function handlePrevious() {
    if (currentPage > 1) {
      currentPage = currentPage - 1;
      onpagechange(currentPage);
    }
  }

  function handleNext() {
    if (currentPage < totalPages) {
      currentPage = currentPage + 1;
      onpagechange(currentPage);
    }
  }

  function handlePageClick(pageNum: number) {
    currentPage = pageNum;
    onpagechange(pageNum);
  }
</script>

{#if totalPages > 0}
  <div class={styles.pagination}>
    {#if currentPage > 1}
      <button
        onclick={handlePrevious}
        class={styles.pageButton}
        aria-label="이전 페이지"
      >
        <i class="icon-arrow-left"></i>
      </button>
    {:else}
      <div class={styles.pageButtonPlaceholder}></div>
    {/if}

    {#each pageNumbers as pageNum (pageNum)}
      <button
        onclick={() => handlePageClick(pageNum)}
        class="{styles.pageButton} {currentPage === pageNum ? styles.active : ''}"
        aria-label="{pageNum}페이지"
        aria-current={currentPage === pageNum ? 'page' : undefined}
      >
        {pageNum}
      </button>
    {/each}

    {#if currentPage < totalPages}
      <button
        onclick={handleNext}
        class={styles.pageButton}
        aria-label="다음 페이지"
      >
        <i class="icon-arrow-right"></i>
      </button>
    {:else}
      <div class={styles.pageButtonPlaceholder}></div>
    {/if}
  </div>
{/if}

// react/molecule/pagination.tsx
import styles from './pagination.module.scss';

interface PaginationProps {
  currentPage: number;
  totalPages: number;
  onPageChange: (page: number) => void;
  maxVisiblePages?: number;
}

export default function Pagination({
  currentPage,
  totalPages,
  onPageChange,
  maxVisiblePages = 5,
}: PaginationProps) {
  const getPageNumbers = () => {
    const pages: number[] = [];
    const startPage = Math.floor((currentPage - 1) / maxVisiblePages) * maxVisiblePages + 1;
    const endPage = Math.min(startPage + maxVisiblePages - 1, totalPages);

    for (let i = startPage; i <= endPage; i++) {
      pages.push(i);
    }

    return pages;
  };

  const pageNumbers = getPageNumbers();

  const handlePrevious = () => {
    if (currentPage > 1) {
      onPageChange(currentPage - 1);
    }
  };

  const handleNext = () => {
    if (currentPage < totalPages) {
      onPageChange(currentPage + 1);
    }
  };

  if (totalPages === 0) {
    return null;
  }

  return (
    <div className={styles.pagination}>
      {currentPage > 1 ? (
        <button
          onClick={handlePrevious}
          className={styles.pageButton}
          aria-label="이전 페이지"
        >
          <i className="icon-arrow-left"></i>
        </button>
      ) : (
        <div className={styles.pageButtonPlaceholder} />
      )}

      {pageNumbers.map((pageNum) => (
        <button
          key={pageNum}
          onClick={() => onPageChange(pageNum)}
          className={`${styles.pageButton} ${
            currentPage === pageNum ? styles.active : ''
          }`}
          aria-label={`${pageNum}페이지`}
          aria-current={currentPage === pageNum ? 'page' : undefined}
        >
          {pageNum}
        </button>
      ))}

      {currentPage < totalPages ? (
        <button
          onClick={handleNext}
          className={styles.pageButton}
          aria-label="다음 페이지"
        >
          <i className="icon-arrow-right"></i>
        </button>
      ) : (
        <div className={styles.pageButtonPlaceholder} />
      )}
    </div>
  );
}
