// svelte/molecule/ToastProvider.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { onMount } from 'svelte';
  import {
    createToastContext,
    type ToastPosition,
  } from '../stores/toast';
  import Toast from './Toast.svelte';
  import { portal } from '../actions/portal';
  import styles from './toast-container.module.scss';

  interface Props {
    /** Children content */
    children?: Snippet;
  }

  let { children }: Props = $props();

  const { toasts, hideToast } = createToastContext();

  const positions: ToastPosition[] = [
    'top-left',
    'top-center',
    'top-right',
    'center-left',
    'center',
    'center-right',
    'bottom-left',
    'bottom-center',
    'bottom-right',
  ];

  let isMounted = $state(false);

  onMount(() => {
    isMounted = true;
    return () => {
      isMounted = false;
    };
  });

  function getToastsByPosition(position: ToastPosition) {
    return $toasts.filter((t) => t.position === position);
  }
</script>

{#if children}
  {@render children()}
{/if}

{#if isMounted}
  <div class={styles.toastPortal} use:portal={'body'}>
    {#each positions as position (position)}
      {@const positionToasts = getToastsByPosition(position)}
      {#if positionToasts.length > 0}
        <div class="{styles.toastContainer} {styles[position]}">
          {#each positionToasts as toast (toast.id)}
            <Toast
              id={toast.id}
              header={toast.header}
              message={toast.message}
              theme={toast.theme}
              border={toast.border}
              long={toast.long}
              duration={toast.duration}
              width={toast.width}
              onclose={() => hideToast(toast.id)}
            />
          {/each}
        </div>
      {/if}
    {/each}
  </div>
{/if}

// react/molecule/toast-provider.tsx
'use client';

import React, { createContext, useContext, useState, useCallback } from 'react';
import { createPortal } from 'react-dom';
import Toast, { ToastProps, ToastPosition, ToastTheme } from './toast';
import styles from './toast-container.module.scss';

interface ToastData extends Omit<ToastProps, 'id' | 'onClose'> {
  id: string;
  position: ToastPosition;
}

interface ToastOptions {
  header?: string;
  message: string;
  theme?: ToastTheme;
  border?: boolean;
  long?: boolean;
  duration?: number;
  width?: string | number;
  position?: ToastPosition;
}

interface ToastContextType {
  showToast: (options: ToastOptions) => string;
  hideToast: (id: string) => void;
}

const ToastContext = createContext<ToastContextType | undefined>(undefined);

export const useToast = () => {
  const context = useContext(ToastContext);
  if (!context) {
    throw new Error('useToast must be used within ToastProvider');
  }
  return context;
};

export const ToastProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [toasts, setToasts] = useState<ToastData[]>([]);
  const [isMounted, setIsMounted] = useState(false);

  React.useEffect(() => {
    setIsMounted(true);
  }, []);

  const showToast = useCallback((options: ToastOptions): string => {
    const id = `toast-${Date.now()}-${Math.random()}`;
    const position = options.position || 'top-right';

    setToasts((prev) => [
      ...prev,
      {
        id,
        position,
        header: options.header,
        message: options.message,
        theme: options.theme,
        border: options.border,
        long: options.long,
        duration: options.duration,
        width: options.width,
      },
    ]);

    return id;
  }, []);

  const hideToast = useCallback((id: string) => {
    setToasts((prev) => prev.filter((toast) => toast.id !== id));
  }, []);

  const getToastsByPosition = (position: ToastPosition) => {
    return toasts.filter((toast) => toast.position === position);
  };

  const positions: ToastPosition[] = [
    'top-left',
    'top-center',
    'top-right',
    'center-left',
    'center',
    'center-right',
    'bottom-left',
    'bottom-center',
    'bottom-right',
  ];

  return (
    <ToastContext.Provider value={{ showToast, hideToast }}>
      {children}
      {isMounted &&
        createPortal(
          <div className={styles.toastPortal}>
            {positions.map((position) => {
              const positionToasts = getToastsByPosition(position);
              if (positionToasts.length === 0) return null;

              return (
                <div key={position} className={`${styles.toastContainer} ${styles[position]}`}>
                  {positionToasts.map((toast) => (
                    <Toast
                      key={toast.id}
                      id={toast.id}
                      header={toast.header}
                      message={toast.message}
                      theme={toast.theme}
                      border={toast.border}
                      long={toast.long}
                      duration={toast.duration}
                      width={toast.width}
                      onClose={hideToast}
                    />
                  ))}
                </div>
              );
            })}
          </div>,
          document.body
        )}
    </ToastContext.Provider>
  );
};
